<?php

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

class Mailer
{

	/**
	 * This method sends a email
	 *
	 * @param	string	$fro	 	Email address origin 
	 * @param	string	$to			Email addess destination
	 * @param	string	$name		Name of addressee
	 * @param	string	$subject	Topic of message
	 * @param	string	$html		Message HTML
	 * @param	string	$text		Message simple
	 *
	 * @return	boolean
	 */
	public static function send($to, $name, $charge)
	{
		$mail = new PHPMailer(true);						// Passing `true` enables exceptions
			
		//Server settings
		$mail->SMTPDebug	=	0;							// Enable verbose debug output
		$mail->isSMTP();
		$mail->Host = "smtp-relay.sendinblue.com";
		$mail->SMTPAuth = true;
		$mail->Username = 'a14021414@iteshu.edu.mx'; //paste one generated by Mailtrap
		$mail->Password = "vURaf7sCcg3hHy6Z";  //paste one generated by Mailtrap
		$mail->SMTPSecure = 'tls';
		$mail->Port = 587;

		$mail->setFrom('guslopezcallejas@gmail.com', 'Mailtrap');
		$mail->addAddress($to, $name);


		$mail->Subject = "Comprobante de pago";

		$mail->isHTML(true);

		$message  = "<html><body>";
   
$message .= "<div>
<TABLE WIDTH=627 CELLPADDING=7 CELLSPACING=0 STYLE='page-break-before: always'>
	<COL WIDTH=298>
	<COL WIDTH=298>
	<TR>
		<TD COLSPAN=2 WIDTH=611 HEIGHT=98 VALIGN=TOP BGCOLOR='#4472c4' STYLE='border: 1px solid #4472c4; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><FONT SIZE=6 STYLE='font-size: 22pt'><B>Envió un
			pago de $3,501.00 MXN a LINIO (</B></FONT><A HREF='mailto:contacto.mx@linio.com'><FONT COLOR='#ffffff'><FONT SIZE=6 STYLE='font-size: 22pt'><B>contacto.mx@linio.com</B></FONT></FONT></A><FONT SIZE=6 STYLE='font-size: 22pt'><B>)</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD COLSPAN=2 WIDTH=611 HEIGHT=27 VALIGN=TOP BGCOLOR='#d9e2f3' STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P><B><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><SPAN LANG='es-MX'><SPAN STYLE='background: #ffffff'>Puede
			tomar unos minutos que esta transacción aparezca en su cuenta</SPAN></SPAN></FONT></FONT></B></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=298 HEIGHT=24 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER STYLE='margin-top: 0.19in'><FONT FACE='Times New Roman, serif'><FONT SIZE=3><B><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'>Id.
			de transacción</FONT></FONT></B></FONT></FONT></P>
		</TD>
		<TD WIDTH=298 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><A HREF='https://www.paypal.com/myaccount/transaction/details/1LB93228DK4833319?v=1&amp;utm_source=unp&amp;utm_medium=email&amp;utm_campaign=RT000016&amp;utm_unptid=&amp;ppid=RT000016&amp;cnac=MX&amp;rsta=es_XC(es-MX)&amp;cust=&amp;unptid=&amp;calc=4716b9ddc915c&amp;unp_tpcid=null&amp;page=main%3Aemail%3ART000016&amp;pgrp=main%3Aemail&amp;e=cl&amp;mchn=em&amp;s=ci&amp;mail=sys&amp;appVersion=1.31.0&amp;xt=104038'><FONT COLOR='#1155cc'><FONT FACE='Helvetica, serif'><SPAN STYLE='background: #ffffff'>1LB93228DK4833319</SPAN></FONT></FONT></A></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=298 HEIGHT=14 BGCOLOR='#d9e2f3' STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><B><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><SPAN STYLE='background: #ffffff'>Fecha
			de la transacción</SPAN></FONT></FONT></B></P>
		</TD>
		<TD WIDTH=298 BGCOLOR='#d9e2f3' STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><SPAN LANG='es-MX'>XXXXX</SPAN></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=298 HEIGHT=12 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><B><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><SPAN STYLE='background: #ffffff'>Comercio</SPAN></FONT></FONT></B></P>
		</TD>
		<TD WIDTH=298 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><SPAN STYLE='background: #ffffff'>LINIO</SPAN></FONT></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=298 HEIGHT=12 BGCOLOR='#d9e2f3' STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><BR>
			</P>
		</TD>
		<TD WIDTH=298 BGCOLOR='#d9e2f3' STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P ALIGN=CENTER><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=298 HEIGHT=24 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P STYLE='margin-top: 0.19in'><BR>
			</P>
		</TD>
		<TD WIDTH=298 STYLE='border: 1px solid #8eaadb; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0.08in'>
			<P LANG='es-MX'><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P LANG='es-MX' STYLE='margin-bottom: 0.11in'><BR><BR>
</P>
<P STYLE='margin-bottom: 0in; background: #ffffff; line-height: 0.25in'>
<FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><FONT SIZE=3><SPAN LANG='es-MX'><B>¿Tiene
problemas con esta transacción?</B></SPAN></FONT></FONT></FONT></P>
<TABLE WIDTH=100% CELLPADDING=5 CELLSPACING=0 BGCOLOR='#ffffff'>
	<COL WIDTH=256*>
	<TR>
		<TD WIDTH=100% BGCOLOR='#ffffff' STYLE='border: none; padding: 0in'>
			<P><FONT COLOR='#2c2e2f'><FONT FACE='Helvetica, serif'><FONT SIZE=3><SPAN LANG='es-MX'>Dispone
			de 180 días desde la fecha de la transacción para presentar una
			controversia en el Centro de resoluciones.</SPAN></FONT></FONT></FONT></P>
		</TD>
	</TR>
</TABLE>
<P STYLE='margin-bottom: 0.11in'><BR><BR>
</P>
</div>";
   
$message .= "</body></html>";

		// Envia estructura
		$mail->Body = $message;

		$mail->SMTPOptions = [
    	'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true,
    	]
		];

if ($mail->send()) {
    return true;
} else {
    return false;
}	}

}

?>