# Site settings
lang: en-US
title: REST Api with Slim PHP
description: This API works with the same concept of social network of Fav Quote.

# About/contact
author:
  name: Manuel Gil
  picture: https://avatars0.githubusercontent.com/u/25472045?s=400&v=4
  twitter_username:
  github_username: ManuelGil

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
show_downloads: true
google_analytics:
